FROM cpa2dev.kyivstar.ua/alpine-oracle-jdk8-bash

COPY ./target/client-event-handler.jar /client-event-handler
WORKDIR /cpa-provider-io

RUN ["chown", "-R", "daemon:daemon", "."]
RUN ["mkdir", "-p", "logs"]
RUN ["chown", "-R", "daemon:daemon", "logs"]

EXPOSE 8079 8080

USER daemon

ENV JAVA_OPTS "-Xmx300m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8078"
CMD ["bin/client-event-handler", "8081"]

